version: 2
updates:
  # Enable version updates for Flutter/Dart
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "zephyrui/core-team"
    assignees:
      - "zephyrui/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "flutter"
    ignore:
      # Ignore specific dependency updates that might cause breaking changes
      - dependency-name: "flutter"
        versions: ["4.0.0"]
      - dependency-name: "dart"
        versions: ["4.0.0"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "zephyrui/core-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"

  # Enable version updates for npm (used in documentation tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "zephyrui/core-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "documentation"