# This file contains the analysis options used by Dart and Flutter tools.
# Visit https://dart.dev/guides/language/analysis-options for documentation.

include: package:flutter_lints/flutter.yaml

# Additional rules for ZephyrUI project
analyzer:
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/**/*.mocks.dart"
    - "build/**"
    - "doc/api/**"
    - "**/node_modules/**"
  
  errors:
    # Treat these as errors
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    todo: ignore
    
  plugins:
    - custom_linter

linter:
  rules:
    # Additional recommended rules (updated for Dart 3.3+)
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_types_as_parameter_names
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - valid_regexps
    - void_checks

# Custom rules for ZephyrUI
# Add custom lint rules here
custom_linter:
  rules:
    # Component naming conventions
    - component_naming_convention
    - theme_property_naming
    - accessibility_property_naming
    
    # Performance rules
    - avoid_expensive_builds
    - prefer_const_constructors_in_widgets
    - avoid_unnecessary_setState
    
    # Documentation rules
    - public_api_documentation
    - example_code_documentation
    - parameter_documentation
    
    # Security rules
    - no_hardcoded_secrets
    - secure_webview_usage
    - input_validation
    
    # Testing rules
    - test_naming_convention
    - test_coverage_rules
    - mock_usage_rules

# Code coverage requirements
coverage:
  minimum: 85
  paths:
    - lib/
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.mocks.dart
    - lib/src/generated/

# Performance thresholds
performance:
  max_build_time_ms: 100
  max_memory_usage_mb: 50
  max_frame_time_ms: 16

# Security settings
security:
  check_dependencies: true
  check_hardcoded_secrets: true
  check_insecure_apis: true
  check_webview_security: true
