name: Bug Report
description: Report a bug to help us improve ZephyrUI
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the bug
      placeholder: Brief description of the issue
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Use this component...
        2. With these parameters...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Code that reproduces the issue
      render: dart
      placeholder: |
        // Your code here
        ZephyrButton(
          text: 'Example',
          onPressed: () {},
        )

  - type: input
    id: version
    attributes:
      label: ZephyrUI Version
      description: What version of ZephyrUI are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: What version of Flutter are you using?
      placeholder: "3.19.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Android
        - iOS
        - Web
        - Windows
        - macOS
        - Linux
        - Multiple
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information about the issue
      placeholder: Screenshots, error messages, logs, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/zephyrui/zephyr_ui/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a minimal reproduction case
          required: true
        - label: I have included all necessary information
          required: true