name: Feature Request
description: Suggest a new feature for ZephyrUI
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for ZephyrUI!
        
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature
      placeholder: Brief description of the requested feature
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: A detailed description of the feature
      placeholder: |
        What would you like to see implemented?
        Why would this feature be useful?
        How would it work?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature
      placeholder: |
        As a [type of user],
        I want [some goal],
        so that [some reason].

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to be implemented?
      placeholder: Describe your preferred solution approach

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered
      placeholder: Any alternative approaches or workarounds

  - type: textarea
    id: code-example
    attributes:
      label: Code Example (Optional)
      description: How would you like to use this feature?
      render: dart
      placeholder: |
        // How you'd like to use the new feature
        ZephyrNewComponent(
          property: value,
          // ...
        )

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/zephyrui/zephyr_ui/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear and detailed description
          required: true
        - label: I have included relevant use cases and examples
          required: true