# Production Configuration
app_name: "chromaUI"
version: "1.0.0"
environment: "production"

# API Configuration
api:
  base_url: "https://api.chroma-ui.dev"
  timeout: 30000
  connect_timeout: 15000
  headers:
    "Content-Type": "application/json"
    "Accept": "application/json"
    "X-API-Key": "${chroma_API_KEY}"
  enable_logging: false

# Theme Configuration
theme:
  primary_color: "#1976D2"
  secondary_color: "#F57C00"
  font_family: "Inter"
  border_radius: 8.0
  enable_dark_mode: true

# Feature Configuration
features:
  enable_analytics: true
  enable_crash_reporting: true
  enable_performance_monitoring: true
  enable_offline_mode: true
  enabled_modules:
    - "basic_components"
    - "form_components"
    - "display_components"
    - "layout_components"
    - "navigation_components"
    - "feedback_components"
    - "advanced_components"

# Analytics Configuration
analytics:
  tracking_id: "UA-PROD-123456"
  enable_tracking: true
  custom_properties:
    environment: "production"
    version: "1.0.0"

# Logging Configuration
logging:
  level: "INFO"
  enable_console: false
  enable_file: true
  max_file_size: 10485760  # 10MB
  max_files: 10
